name: Daily Commit Action

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: '0 12 * * *'

jobs:
  "24f2004275@ds.study.iitm.ac.in":
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add a commit with a timestamp to the repository
      - name: Create daily commit
        run: |
          echo "Commit made on $(date)" >> commit_log.txt
          git add commit_log.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Daily commit on $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}